version: '3.1'
services:
  rabbitmq:
    container_name: rabbitmq
    restart: always
    image: rabbitmq:3.10-rc-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASSWORD}
    ports:
      - ${RABBITMQ_GUI_MANAGER_PORT}:${RABBITMQ_GUI_MANAGER_PORT}
    networks:
      - free_lunch_app
    healthcheck:
      test: "exit 0"

  mysql:
    container_name: mysql
    restart: always
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD_ROOT}
      MYSQL_USER: ${MYSQL_USERNAME_ADMIN}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD_ADMIN}
      LANG: 'en_US.UTF-8'
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    networks:
      - free_lunch_app
    volumes:
      - ./mysql_scripts:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql

  mongodb:
    container_name: mongodb
    image: mongo:5.0.27
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME_ADMIN}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD_ADMIN}
    ports:
      - ${MONGODB_HOST_PORT}:${MONGODB_PORT}
    networks:
      - free_lunch_app
    volumes:
      - ./mongodb_scripts:/docker-entrypoint-initdb.d
      - mongodb_data:/data/db
        
  api_gateway:
    container_name: api_gateway
    restart: always
    build:
      context: ./api_gateway
      target: production
    env_file:
      - ./api_gateway/.env
    environment:
      - PORT=${API_GATEWAY_PORT}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    ports:
      - ${API_GATEWAY_PORT}:${API_GATEWAY_PORT}
    networks:
      - free_lunch_app
    volumes:
      - ./shared:/usr/share/docker
      - ./api_gateway:/usr/app
      - ./api_gateway/node_modules:/usr/app/node_modules
    depends_on:
      - auth_service
      - kitchen_service
      - inventory_service
      - supply_service

  auth_service:
    container_name: auth_service
    restart: always
    build:
      context: ./auth_service
      target: production
    env_file:
      - ./auth_service/.env
    environment:
      - PORT=${AUTH_SERVICE_PORT}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    networks:
      - free_lunch_app
    volumes:
      - ./shared:/usr/share/docker
      - ./auth_service:/usr/app
      - ./auth_service/node_modules:/usr/app/node_modules
      - ./auth_service/dist:/usr/app/dist
    depends_on:
      mysql:
        condition: service_started

  kitchen_service:
    container_name: kitchen_service
    restart: always
    build:
      context: ./kitchen_service
      target: production
    env_file:
      - ./kitchen_service/.env
    environment:
      - PORT=${KITCHEN_SERVICE_PORT}
    networks:
      - free_lunch_app
    volumes:
      - ./shared:/usr/share/docker
      - ./kitchen_service:/usr/app
      - ./kitchen_service/node_modules:/usr/app/node_modules
      - ./kitchen_service/dist:/usr/app/dist
    depends_on:
      mongodb:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  inventory_service:
    container_name: inventory_service
    restart: always
    build:
      context: ./inventory_service
      target: production
    env_file:
      - ./inventory_service/.env
    environment:
      - PORT=${INVENTORY_SERVICE_PORT}
    volumes:
      - ./shared:/usr/share/docker
      - ./inventory_service:/usr/app
      - ./inventory_service/node_modules:/usr/app/node_modules
      - ./inventory_service/dist:/usr/app/dist
    networks:
      - free_lunch_app
    depends_on:
      mysql:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  supply_service:
    container_name: supply_service
    restart: always
    build:
      context: ./supply_service
      target: production
    env_file:
      - ./supply_service/.env
    environment:
      - PORT=${SUPPLY_SERVICE_PORT}
    volumes:
      - ./shared:/usr/share/docker
      - ./supply_service:/usr/app
      - ./supply_service/node_modules:/usr/app/node_modules
      - ./supply_service/dist:/usr/app/dist
    networks:
      - free_lunch_app
    depends_on:
      mysql:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  restaurant_frontend_app: 
    container_name: restaurant_frontend_app
    restart: always
    build:
      context: ./restaurant_frontend_app
      target: production
    environment:
      - PORT=${RESTAURANT_FRONTEND_APP_PORT}
    ports:
      - ${RESTAURANT_FRONTEND_APP_PORT}:${RESTAURANT_FRONTEND_APP_PORT}
    networks:
      - free_lunch_app
    volumes:
      - ./shared:/usr/share/docker
      - ./restaurant_frontend_app:/usr/app
      - ./restaurant_frontend_app/node_modules:/usr/app/node_modules
      - ./restaurant_frontend_app/dist:/usr/share/nginx/html
    depends_on:
      - api_gateway

networks:
  free_lunch_app:
    driver: bridge

volumes:
  mysql_data:
  mongodb_data: